#!/usr/bin/env python3
"""
Generate a Markdown pull-request body for the Docker security patch PR.

Reads context from environment variables (set by the GitHub Actions step):
  PATCHED_IMAGE     - final verified patched image tag
  PATCH_PLAN_PATH   - path to the patch_plan_*.json produced by the patcher
  DOCKERFILE_PATH   - original Dockerfile path (for display only)
  GITHUB_RUN_ID     - GitHub Actions run ID (for traceability)

Writes the Markdown body to stdout so the caller can redirect it to a file.
"""
from __future__ import annotations

import json
import os
import sys


def main() -> None:
    patched_image   = os.environ.get("PATCHED_IMAGE", "")
    patch_plan_path = os.environ.get("PATCH_PLAN_PATH", "")
    dockerfile      = os.environ.get("DOCKERFILE_PATH", "Dockerfile")
    run_id          = os.environ.get("GITHUB_RUN_ID", "")

    rows: list[str] = []
    total = 0

    if patch_plan_path and os.path.exists(patch_plan_path):
        try:
            with open(patch_plan_path, encoding="utf-8") as fh:
                plan: list[dict] = json.load(fh)
            total = len(plan)
            for item in plan[:30]:
                sev = item.get("severity", "")
                rows.append(
                    f"| `{item.get('cve_id', '')}` "
                    f"| {item.get('package', '')} "
                    f"| `{item.get('from', '')}` "
                    f"| `{item.get('to', '')}` "
                    f"| **{sev}** |"
                )
        except Exception as exc:  # noqa: BLE001
            rows = [f"| _(could not parse patch plan: {exc})_ | | | | |"]

    if rows:
        cve_table = (
            "| CVE ID | Package | From | To | Severity |\n"
            "|--------|---------|------|----|----------|\n"
            + "\n".join(rows)
        )
        if total > 30:
            cve_table += f"\n\n_{total - 30} additional CVEs not shown — see `patch_plan.json`._"
    else:
        cve_table = "_No CVE data available._"

    body_parts = [
        "## Docker Security Patch",
        "",
        (
            "> Automatically generated by "
            "[patch-docker-image](https://github.com/qasimnauman/patch-docker-image) "
            "after a successful **zero-CVE** post-patch Docker Scout verification scan "
            f"(workflow run `{run_id}`)."
        ),
        "",
        "### What this PR contains",
        "",
        "| File | Description |",
        "|------|-------------|",
        f"| `Dockerfile.patched` | Drop-in replacement for `{dockerfile}` with all fixable CVEs resolved |",
        "| `patch_plan.json` | Machine-readable list of every CVE addressed |",
        "",
        "### Verified patched image",
        "",
        "```",
        patched_image,
        "```",
        "",
        f"### CVEs addressed ({total} total)",
        "",
        cve_table,
        "",
        "### How to apply",
        "",
        f"1. **Review** `Dockerfile.patched` — inspect the generated `RUN` patch layers.",
        f"2. **Replace** your `{dockerfile}` with `Dockerfile.patched`, or cherry-pick the `RUN` layers.",
        "3. **Merge** this PR to record the security fix in your repo history.",
        "",
        "---",
        (
            "*The patched image tag above is only available in the runner's Docker daemon "
            "for the duration of this workflow run. Re-build from `Dockerfile.patched` to reproduce it.*"
        ),
    ]

    sys.stdout.write("\n".join(body_parts) + "\n")


if __name__ == "__main__":
    main()
